---
title: "Shai Gilgeous-Alexander 2024-25 Points"
format: html
---

The 2024-25 NBA season was a historic one for the Oklahoma City Thunder, who captured their first ever NBA Championship. The NBA Playoffs consist of four rounds, First Round, Second Round, Conference Finals, and NBA Finals, with each round played as a best of seven series. In the 2025, playoffs, the Thunder played a total of 23 games: 4 in the First Round, 7 in the Second Round, 5 in the Conference Finals, and 7 in the NBA Finals.

At the heart of this title run was Shai Gilgeous-Alexander (SGA), who led the league in scoring, was named NBA MVP and capped off the season by earning the Finals MVP. His scoring consistency and ability to take over games made him one of the most dominant offensive forces in the league. This dataset, which contains SGA's point totals from every regular season game, offers a snapshot of one of the most impressive individual season in recent NBA history.

In addition to its basketball significance, this dataset allows us to explore how statistical tools (such as StatKey) can be used to simulate real-world scenarios. By treating SGA's regular season point totals as the population, we can model specific playoff situations by drawing random samples of different sizes. These simulations help us understand how much variation we might expect in his performances and how likely different playoff outcomes are are based on his regular season scoring.


1. Here is a dotplot of SGA's game-by-game point totals from the 2024-25 regular season.

```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)

sga <- read_csv("sga_points_2025.csv")

sga |>
  ggplot(., aes(x = points)) +
  geom_dotplot(binwidth = 1, 
               color = rgb(239,59,36, maxColorValue = 255),
               fill = rgb(0,125,195, maxColorValue = 255),
               stroke = 1.5,
               method = "histodot") +
  scale_x_continuous(breaks = c(15, 20, 25, 30, 35, 40, 45, 50, 55))
```

Describe the shape, center and spread.



# 2. Simulating an NBA Finals Scenario

In StatKey go to Sampling Distribution for a Mean. Upload the **sga_points_2025.csv** file and select the points column as the population. Set the sample size to 7 to mimic the 2025 NBA Finals series, and generate 1000 samples.

a. Describe the shape, center, and spread of the sampling distribution you generated.
  
  
  
b. SGA's actual points per game in the 2025 NBA Finals was 30.3. Based on your sampling distribution, does this seem unusually high, unusually low, or fairly typical? Explain your reasoning.



# 3. Simulating an NBA Playoffs Scenario

Now set the sample size to 23 to mimic the Oklahoma City Thunder's 2025 playoff run, and generate 1000 samples

a. Describe the shape, center, and spread of the sampling distribution you generated.
  
  
  
b. SGA's actual points per game in the 2025 NBA Playoffs was 29.9. Based on your sampling distribution, does this seem unusually high, unusually low, or fairly typical? Explain your reasoning.



# 4. General Rules and Trends

Based on your two simulations, using sample sizes of 7 and 23, what general patterns or trends do you notice about the shape, center, and spread of the sampling distributions? 



# 5. Central Limit Theorem

As the sample size increased from 7 to 23, the sampling distributions began to look more symmetric and bell-shaped. Why do you think this happened? What kind of distribution does the sampled means seem to resemble?


