---
title: "Shai Gilgeous-Alexander 2024-25 Points Solutions"
format: docx
---

The 2024-25 NBA season was a historic one for the Oklahoma City Thunder, who captured their first ever NBA Championship. The NBA Playoffs consist of four rounds, First Round, Second Round, Conference Finals, and NBA Finals, with each round played as a best of seven series. In the 2025, playoffs, the Thunder played a total of 23 games: 4 in the First Round, 7 in the Second Round, 5 in the Conference Finals, and 7 in the NBA Finals.

At the heart of this title run was Shai Gilgeous-Alexander (SGA), who led the league in scoring, was named NBA MVP and capped off the season by earning the Finals MVP. His scoring consistency and ability to take over games made him one of the most dominant offensive forces in the league. This dataset, which contains SGA's point totals from every regular season game, offers a snapshot of one of the most impressive individual season in recent NBA history.

In addition to its basketball significance, this dataset allows us to explore how statistical tools (such as StatKey) can be used to simulate real-world scenarios. By treating SGA's regular season point totals as the population, we can model specific playoff situations by drawing random samples of different sizes. These simulations help us understand how much variation we might expect in his performances and how likely different playoff outcomes are are based on his regular season scoring.


1. Here is a dotplot of SGA's game-by-game point totals from the 2024-25 regular season.

```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)

sga <- read_csv(here::here("colney/nba_sampling_distributions/data_repo_submission/sga_points_2025.csv"))

sga %>%
  ggplot(., aes(x = points)) +
  geom_dotplot(binwidth = 1, 
               color = rgb(239,59,36, maxColorValue = 255),
               fill = rgb(0,125,195, maxColorValue = 255),
               stroke = 1.5,
               method = "histodot") +
  scale_x_continuous(breaks = c(15, 20, 25, 30, 35, 40, 45, 50, 55))
```

Describe the shape, center and spread.

Solution: Shape: The distribution is slightly right-skewed, most games fall between 25 and 40, but there are a couple games in the high 40's and 50's that stretch the right tail of the distribution. Center: The center appears to be around 32, which is right around his season points per game of 32.5. Spread: The range is 18 to 53, and most games fall between 25 and 40.

# 2. Simulating an NBA Finals Scenario

In StatKey go to Sampling Distribution for a Mean. Upload the **sga_points_2025.csv** file and select the points column as the population. Set the sample size to 7 to mimic the 2025 NBA Finals series, and generate 1000 samples.

a. Describe the shape, center, and spread of the sampling distribution you generated.

Solution: Shape: The sampling distribution is roughly symmetric. Center: The mean of the sampling distribution is 32.504. Spread: The range is roughly between 25 and 42, with most games between 30 and 35. Also, std dev = 1.07

b. SGA's actual points per game in the 2025 NBA Finals was 30.3. Based on your sampling distribution, does this seem unusually high, unusually low, or fairly typical? Explain your reasoning.

Solution: SGA's actual ppg falls below the mean of the sampling distribution. Approximately 23.1% of simulated sample means were less than or equal to 30.3. Even though it fall below the mean, it is still fairly typical.

# 3. Simulating an NBA Playoffs Scenario

Now set the sample size to 23 to mimic the Oklahoma City Thunder's 2025 playoff run, and generate 1000 samples

a. Describe the shape, center, and spread of the sampling distribution you generated.

Solution: Shape: The sampling distribution is roughly symmetric. Center: The mean of the sampling distribution is 32.496. Spread: The range is roughly between 29 and 37, with most games between 31 and 34. Also, std dev = 0.27

b. SGA's actual points per game in the 2025 NBA Playoffs was 29.9. Based on your sampling distribution, does this seem unusually high, unusually low, or fairly typical? Explain your reasoning.

Solution: SGA's actual ppg falls below the mean of sampling distribution. Approximately 2.1% of simulated sample means were less than or equal to 29.9. This is unusually low and suggests that is entire playoff scoring was lower than we'd typically expect.

# 4. General Rules and Trends

Based on your two simulations, using sample sizes of 7 and 23, what general patterns or trends do you notice about the shape, center, and spread of the sampling distributions? 

Solution: Shape: When n = 23, the distribution was much smoother and more bell-shaped, when n = 7 it was more irregular and bumpy. Center: In both simulations, the sampling distributions were centered close to the same value of 32.5, which matches the mean of the original population. Spread: The std. dev was larger when n = 7 (1.07) and smaller when n = 23 (0.27). Meaning that larger samples lead to more consistent sample means.

# 5. Central Limit Theorem

As the sample size increased from 7 to 23, the sampling distributions began to look more symmetric and bell-shaped. Why do you think this happened? What kind of distribution does the sampled means seem to resemble?

Solution: As the sample size increased, the sample means became more consistent and less spread out. Extreme values had less impact, making the distribution more predictable. The sampling distribution with n = 23 looked more symmetric and bell-shaped, similar to a normal distribution. This suggests that larger samples lead to sample distributions that more closely resemble the normal model.