---
title: "FINA World Junior Championships 2022 Diving Data"
date: April 15, 2024
description: Preliminary diving results of womens 16-18 1m springboard from the 2022 FINA World Junior Championships.
author:
  - name: Emma Deering
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Robin Lock
    email: rlock@stlawu.edu
    affiliation:
      - ref: slu
editor: 
  canonical: true
categories:
  - ANOVA for difference in means
  - Pairwise Comparisons
  - Fisher’s LSD
  - Tukey’s HSD
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

The FINA Junior World Diving Championships is a elite dive meet where top divers around the world under the age of 18 compete. Each diver completed 9 dives, all of which contributed to their overall score. Each dive is scored by 7 judges. Each judge gives a score individually on a scale of 1-10 at half-point increments based on execution of the dive. 10 represents perfect execution, while 0 represents failed execution. The two lowest and the two highest scores of the judges are voided, and the other three are added together. The sum of the three judges is then multiplied by the difficulty of the attempted dive. The product represent the points earned for that dive. The overall score is calculated by adding together the points earned on each dives.

In this worksheet, we will determine if there are statistical differences in mean total points scored between 16, 17, and 18-year old divers. Understanding how total score differs between different aged divers may tell us something about the importance of age, experince, and skill level in scoring points in diving. 

[Preliminary video ideas](Diving_Video_Topics.docx)

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will be able to:

1.  Conduct and interpret a difference in means hypothesis test.

2.  Conduct and interpret a difference in means ANOVA test.

3.  Understand how mean can differ between groups.
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Technology requirement: The activity handout provides summary statistics so that no statistical software is required. However, the activity could be modified to ask students to conduct hypothesis tests through a statistical software, produce that information from the raw dataset, and/or extend the activity to investigate other variables available in the data.

1.  Hypothesis Tests: Knowledge of hypothesis tests are vital to this activity. Familiarity with  hypothesizes, test statistics, degrees of freedom, and p-values are important for the completion of this worksheet.

2.  ANOVA: Understanding and familiarity with the concept of ANOVA tests are important in order to further analyze the data through pairwise comparisons. 

3.  Familiarity with basic statistical analysis techniques and terms, specifically mean, categorical variables, and quantitative variables, are important conceptual concepts needed in the aiding in this activity.
:::

### Data

The data set contains 360 rows and 15 columns. Each row represents a completed dive from a diver in the preliminary results of women (aged 16-18) 1m springboard from the 2022 FINA World Junior Championships. Each diver completed 9 dives, so there is 9 rows per diver.

Download data: [divingdata.csv](divingdata.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable    | Description                                                    |
|-------------|----------------------------------------------------------------|
| LastName    | The last name of the diver                                     |
| Country     | The country the diver was competing for                        |
| Age         | The age of the diver                                           |
| TotalPoints | The overall points the diver had earned at the end of the meet |
| DiveNum     | The order in which the dives were performed                    |
| DiveName    | The coded name of the dive                                     |
| Difficulty  | The difficulty of the dive                                     |
| Judge1      | The score that judge 1 awarded the dive                        |
| Judge2      | The score that judge 2 awarded the dive                        |
| Judge3      | The score that judge 3 awarded the dive                        |
| Judge4      | The score that judge 4 awarded the dive                        |
| Judge5      | The score that judge 5 awarded the dive                        |
| Judge6      | The score that judge 6 awarded the dive                        |
| Judge7      | The score that judge 7 awarded the dive                        |
| Points      | Overall points the individual dive earned                      |

</details>

#### Data Source

World Aquatics. (2022). FINA World Junior Diving Championships 2022. <https://www.worldaquatics.com/competitions/2951/fina-world-junior-diving-championships-2022/results?event=6d65f6db-1e71-4bca-b1c3-7facf12f500f&unit=preliminary>

### Materials

[Class handout - Two-sample Tests](WS_Diving_TwoSample_Tests.docx) - Comparisons with two-sample tests for means

[Class handout - ANOVA - No data](WS_Diving_ANOVA_No_Data.docx) (summary given - does not require a datafile)

[Class handout - ANOVA - Needs Data](WS_Diving_ANOVA_Needs_Data.docx) (requires the datafile)

[Class handout - Two-sample Tests - Key](WS_Diving_TwoSample_Tests_Key.docx) 


::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}

To Be Written ...
:::

