project:
  type: website
  output-dir: docs

website:
  cookie-consent:
    type: implied
    prefs-text: "Manage cookies"
  title: "SLU SCORE Module Preprint Repository"
  page-footer: 
    center:
      Maintained by Ivan Ramler <br>
    
      We use cookies to track usage statistics 
      to help measure impact of the materials
      for authors. Please consider allowing 
      tracking cookies.
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-statsds-topic.qmd
      - href: https://data.scorenetwork.org/
        text: Data Repository
  sidebar:
    contents: auto
    collapse-level: 1

format:
  html:
    theme:
      - simplex
      - score.scss
    toc: true

execute:
  freeze: auto
