project:
  type: website
  output-dir: docs
  resources:
    - "data/"
    - "materials/"


website:
  title: "SLU SCORE Module Pre-print Repository"
  page-footer: "Maintained by Ivan Ramler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://data.scorenetwork.org/
        text: Data Repository
  sidebar:
    contents: auto
    collapse-level: 1

format:
  html:
    theme:
      - cosmo
      - score.scss
    toc: true

execute:
  freeze: auto
