---
title: "Division Three Volleyball Timeouts"
date: April 18, 2024
author:
  - name: Sierra Hess
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
description: Investigating the effect of timeouts on the outcome of a set. 
editor: 
  canonical: true
categories:
  - One sample proportions 
  - Confidence intervals
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.


### Introduction

In volleyball, timeouts are typically called by the losing team in order to increase their chances of scoring more points in an attempt to win a set. In division three volleyball, teams can call up to three timeouts per set and there are 3 sets per game. 

The [Liberty League](https://libertyleagueathletics.com/sports/wvball) is made up of 12 New York state colleges including St. Lawrence, Clarkson University, Hobart and William Smith Colleges, the University of Rochester, Rensselaer Polytechnic Institute, Skidmore College, Union College, Vassar College, Bard College, Rochester Institute of Technology, and Ithaca College. When looking at the data for the Liberty League division for women's volleyball, we can see exactly when a timeout was called. 

In this worksheet, we will analyze the effects of calling a timeout on a set. We can find the probability that calling a timeout will lead to scoring a point by looking at the outcome of each timeout. By looking only at the first or last timeout of a set, we will be able to determine how likely a losing team is to win that set after calling their first or final timeout. Understanding the effects that a timeout has on a set can inform strategic decision-making for coaches and allow them to understand how much calling a timeout may help their game.


### Welcome video

: [Preliminary script for video](Volleyball_Script.docx)


::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will be able to:

1.  Understand statistical concepts (such as observations/ variable of interest/ categorical vs numerical/ statistic vs parameter/ etc.). 

2.  Create a 95% confidence interval and explain what that interval means.

3.  Identify potential reasons for outcomes. 

:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Technology requirement: The activity handout provides data and summary statistics so that no statistical software is required. However, the activity could be modified to ask students to produce that information from the raw data set and/or extend the activity to investigate other variables available in the data.

1.  Basic mathematical concepts: Familiarity with observations/ variable of interest/ categorical vs numerical/ statistic vs parameter

2.  Confidence interval: Knowledge of how to calculate confidence intervals. 

3.  Familiarity with probability and how to get basic probability.

4.  Use of reasoning to explain outcomes.
:::

::: {.callout-note collapse="true" title="Length of Activity" appearance="minimal"}
Suitable for an in-class example.
:::



### Data

This data set has data from 6,408 rows and 17 columns. Each row represents a timeout in a volleyball game for the NCAA women's volleyball Liberty League games from 2013 until 2022.

The handouts have summarized the relevant data and don't need direct access to the data file.

: [timeout.csv](timeout.csv)

<details>

<summary><b>Variable Descriptions</b></summary>
|Variable               | Description                                          |
|-----------------------|------------------------------------------------------|
|play_description       |Which team called the timeout                         | 
|set                    |The set of the game                                   |
|Date                   |The date of the game                                  |
|Time                   |The set in which the timeout was called               | 
|Site                   |The location of the game                              |
|Attendance             |The number of people in attendance of the game        |
|url                    |The specific url from where the game data was pulled  |
|timeout                |True/ False of weather or not the play was a timeout  |
|prev_home_score        |score of the home team when the timeout was called    |
|prev_visiting_score    |score of the visiting team when the timeout was called|
|next_home_score        |score of the home team after after the next play      |
|next_visiting_score    |score of the visiting team after the next play        |
|losing_team            |the team that had the lower previous score            |
|set_winner             |the team that won the entire set                      |
|losing_team_wins       |weather the previously losing team won the set        |


</details>

#### Data Source

Liberty League data
<https://libertyleagueathletics.com/standings.aspx?standings=168>


### Materials

[Class handout](Volleyball_Worksheet.docx)

[Class handout - with solutions](Volleyball_Worksheet_key.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
In conclusion, the analysis of timeouts in D3 women's volleyball has provided valuable insights into how timeouts can effect a game. One notable finding from this worksheet is that when you are losing before your first timeout, you are more likely to win the set than if you are losing before your last timeout of the set. This result makes sense since calling a timeout earlier on gives you more time to make a comeback. 

The difference in probability of winning a set based on which timeout you look at means that calling a timeout earlier on can greatly increase your chances of winning a set/ game.
:::



