---
title: "Strength Ratios - Flat Dumbbell Press to Barbell Bench Press "
author:
  - name: Vivian Johnson
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
date: "June 13, 2024"
description: "Critically exploring self reported strength ratios."
editor: 
  canonical: true
categories:
  - Data collection methods 
  - One sample means-interval 
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

Weightlifters may be inclined to track the specific ratio between flat dumbbell press and barbell bench press.

A **dumbbell** is a short bar with equal weight on both sides designed to be held in the lifter's hands. [Flat dumbbell press](https://www.youtube.com/watch?v=XMc1N3o-Qyw){target="_blank"} is when the lifter lies on a flat bench with their arms positioned at roughly 45 degree angles, lifts two equal sized dumbbells, brings them back to the chest, and then keeps going.

A **barbell** is similar in shape to a dumbbell, but is a longer, much heavier bar where multiple weighted plates can be placed on either side. [Barbell bench press](https://www.youtube.com/watch?v=SCVCLChPQFY){target="_blank"} is when the lifter lies on a bench with the barbell positioned at their chest, lifts the barbell, and then brings it back down.

The ratio of flat dumbbell press to barbell bench press works to track how much someone is lifting two dumbbells compared to how much they are able to lift the weighted barbell. When calculating the ratio, it was multiplied by two in order to account for the total weight lifted when doing a flat dumbbell press, as there are two dumbbells that would have to be held by the lifter.

**An example of this is as follows:**

*Say Melissa is able to flat dumbbell press two 30 lbs dumbbells. The total amount she can flat dumbbell press is 60 lbs (one dumbbell for each arm). On barbell bench press, she can lift 75 lbs. Her ratio would be calculated by dividing flat dumbbell press by barbell bench press (60/75) which equals 0.8, meaning that Melissa can lift two dumbbells up to 80% as heavy as she can bench press the barbell.*

While both exercises predominately target the chest muscles, each can focus on different secondary muscle groups. Many weightlifters like to track this ratio to work towards specific strength goals and target any weakness in certain muscle groups[^1].

[^1]: Although many weightlifters may use this ratio for tracking progress and examining muscle balance, it isn't an official statistic used in competitions, only a personal one.

For example, if someone's ratio is low (i.e. they can barbell bench press much more than they can flat dumbbell press), it highlights that they might want to work on targeting the secondary muscles used in flat dumbbell press. In this case, these muscles are usually referred to as the [*stabilizer muscles*](https://steelsupplements.com/blogs/steel-blog/stabilizer-muscles-101-what-they-are-why-theyre-important){target="_blank"}. This could mean they rely more on the barbell for their pressing strength and might benefit from incorporating more dumbbell exercises to improve muscle balance and stability.

On the flip side, if someone's ratio is high, it might indicate strong stabilizer muscles and good overall balance. This could mean they have well-developed coordination and muscular control, potentially reducing the risk of injury and enhancing overall athletic performance. However, it might also suggest that their barbell press strength is relatively underdeveloped, implying a need to focus more on barbell training to ensure balanced muscle development or to increase their overall strength.

Finally, a lifter might be interested in being close to the average ratio of dumbbell to barbell press because it indicates a balanced strength development. In particular, this can be useful if they are able to compare themselves to the average from a group of peers. Being close to the average suggests that their training regimen is effective in developing both primary pressing muscles and stabilizer muscles evenly. This balance can contribute to better overall performance, reduced injury risk, and a more well-rounded physique.

The data on the ratio between dumbbell and barbell weightlifting comes from responses in a Reddit thread on the [r/fitness](https://www.reddit.com/r/Fitness/comments/35q4i3/how_much_do_you_dumbbell_flat_bench_compared_to/){target="_blank"} subreddit. People who tend to use the fitness subreddit are likely fitness enthusiasts - including beginners, intermediate, and advanced lifters. This community is diverse, with members ranging from casual gym-goers to serious athletes. As with most social media, typical ages of users on the fitness subreddit tend to be in the younger demographic, often ranging from late teens to early 30s. However, there are still users of all ages, including older individuals who are interested in maintaining their fitness and connecting with the community.

This module involves using the strength ratio to look at dot plots, construct and use confidence intervals, and discuss the effect that data collection methods have on the reliability of the data.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of this activity, you will:

1.  Enhance proficiency in constructing and interpreting confidence intervals.

2. Understand the limitations of using smaller datasets of self-selected individuals.

3.  Explain the importance of obtaining a sample that reaches across multiple audiences.

:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}

Students are expected to have been exposed to one-sample inference for means (most likely t-intervals). Students will also need to have been exposed to general sampling practices - including common biases or problematics sampling schemes such as convenience samples and self-reported data.
:::

::: {.callout-note collapse="true" title="Technology Requirements" appearance="minimal"}
No explicit technology is required, although a calculator is recommended. Additionally, the module worksheets can easily be adapted to be used with statistical software.
:::

### Data

The `dumbbell_barbell_weight_ratio` data set contains observed strength ratios from 18 different weightlifters. Each row represents a different weightlifter.

Data is available on the [SCORE Data Repository Website](https://data.scorenetwork.org){target="_blank"}

Download data: [dumbbell_barbell_weight_ratio.csv](https://data.scorenetwork.org/data/dumbbell_barbell_weight_ratio.csv){target="_blank"}

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable | Description                                             |
|----------|---------------------------------------------------------|
| Ratio    | Flat dumbbell press to barbell bench press weight ratio |

</details>

#### Data Source

[Weight Ratio](https://www.reddit.com/r/Fitness/comments/35q4i3/how_much_do_you_dumbbell_flat_bench_compared_to/){target="_blank"}

The data is sourced from a self-reported Reddit open forum. Users provided their weight for both a flat dumbbell press and a barbell bench press, and it was compiled by another user into the corresponding weight ratio. It is important to note that as this is a self-reported open forum, biases may be introduced that wouldn't otherwise be present.

### Materials

[Class handout](weight_ratio_worksheet.docx)

[Class handout - with solutions](weight_ratio_worksheet_SOLUTIONS.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Upon conclusion, students should recognize that the data collected likely strictly limits which population the resulting confidence interval can be applied to.  Additionally, students should recognize that, even with the limitations of these data, they can still provide value. 

This learning module offers valuable insight into the process of data collection and the role it has in making concrete conclusions. There are some obvious biases in the way the data was collected, those who report their ratios belong to similar audiences, and we can't assume that the sample is representative of a broad population. Nevertheless, it presents a valuable opportunity for thought and good practice at constructing one sample t tests and recognizing the extent to which they can be used.
:::
