---
title: "Lacrosse Faceoff Proportions"
date: February 5, 2024
description: Using data from NCAA Div I lacrosse teams to explore the importance of winning faceoffs
author:
  - name: Jack Fay
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
  - name: A.J. Dykstra
    affiliation:
    - ref: slu
editor: 
  canonical: true      
categories:
  - Hypothesis testing
  - Single proportion
---

### Introduction

In this engaging activity, we explore the exciting sport of NCAA Division I Lacrosse, with a special focus on faceoff percentages—a critical aspect of the game. A faceoff occurs at the start of each quarter and after every goal, where two players compete to gain possession of the ball, setting the stage for their team’s offensive play. Winning a high percentage of faceoffs is often key to controlling the game and can significantly impact a team’s overall performance.

::: {.callout-note collapse="true" title="Video Demonstrating a Faceoff" appearance="minimal"}
```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/yL1z6a96Y1w?si=ysfTXdXWc6ozJu6R" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
```
:::

Our primary goal is to compare a specific team's faceoff performance with overall league statistics for the 2022-2023 season. Through this exploration, we'll introduce you to the concept of one-sample proportion hypothesis testing, a powerful statistical tool widely used in sports analytics. By the end of this exercise, you'll gain a fundamental understanding of hypothesis testing and how it can be practically applied to evaluate team performance in lacrosse and beyond.

::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity would be suitable for an in-class example (of approximately 10 - 20 minutes) or can be modified to be a quiz or part of an exam.
:::

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
1.  Comprehend the concept of one sample proportion hypothesis testing and its relevance in sports statistics.
2.  Analyze and interpret dataset variables related to faceoff percentages in NCAA Division I Lacrosse.
3.  Evaluate a specific team's faceoff performance by comparing it with league-wide statistics using hypothesis testing.
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
Students are expected to have been exposed to the following concepts and use the activity to reinforce their understanding of these methods.

1.  Basic probability and percentages.
2.  Null and alternative hypotheses.
3.  Sample size and sample proportion calculations.
4.  Success-failure condition for hypothesis testing.
5.  Calculation of test statistics (Z-score).
6.  Understanding significance levels (⍺) and p-values.
7.  Drawing conclusions and implications from hypothesis test results.
:::

### Data

Note that because the activity only uses results from one team, students do not necessarily need to directly access this data. However, the activity can easily be adapted to use other teams. Instructors are encouraged to personalize the activity if they so choose.

The data set where the activities statistics come from contains 72 rows and 22 columns. Each row represents the season results for a lacrosse team at the NCAA Division 1 level from the 2022-2023 season.

Download data: [lax_2022_2023.csv](lax_2022_2023.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable              | Description                                                                                                     |
|-----------------------|-----------------------------------------------------------------------------------------------------------------|
| Team                  | college of the team                                                                                             |
| avg_assists           | average assists to goals per game                                                                               |
| avg_caused_turnovers  | average turnovers forced by the team per game                                                                   |
| clearing_pctg         | percentage of successful attempts to earn an offensive opportunity after gaining the ball in the teams own half |
| total_faceoffs        | total faceoffs taken by a team for the season                                                                   |
| faceoff_wins          | total faceoff wins by a team for the season                                                                     |
| faceoff_win_pct       | proportion of total faceoff wins out of total faceoffs                                                          |
| avg_goals             | average goals per game                                                                                          |
| avg_goals_allowed     | average goals allowed by the team per game                                                                      |
| avg_ground_balls      | average loose balls picked up by the team per game                                                              |
| man_down_defense_pctg | proportion of times a team stops the opponent from scoring while man down due to a penalty                      |
| man_up_offense_pctg   | proportion of times the offense scores out of total opportunities while man up                                  |
| avg_scoring_margin    | average margin of goals per game                                                                                |
| opp_clear_pctg        | opponents clearing percentage averaged by game                                                                  |
| avg_points            | average team points per game                                                                                    |
| avg_saves             | average saves per game                                                                                          |
| shot_pctg             | proportion of shots that go in out of total shots                                                               |
| avg_turnovers         | average turnovers that are directly the fault of a player per game                                              |
| W                     | total wins by the team                                                                                          |
| L                     | total losses by the team                                                                                        |
| win_loss_pctg         | proportion of games won out of total games                                                                      |

**Data Source**

The data were collected from the NCAA Website for Men's Lacrosse Division I

<http://stats.ncaa.org/rankings/change_sport_year_div>

Instructors interested in updating the data to a newer season can do so via the following

1.  Go to <http://stats.ncaa.org/rankings/change_sport_year_div>
2.  Select Men's Lacrosse, *season of choice*, Division I, Final Statistics
3.  In the "Teams", download each of the data tables.
4.  Read in each file, join the tables, and do some light cleaning. The code below shows an example used for the 2022-2023 season.

```{r}
#| code-fold: true
#| code-summary: "Show the code"
#| eval: false

library(tidyverse)


# reading
# the files listed here are what
# you will download from the site

assists<- read_csv("assists_l.csv", col_select = 1:2)
caused_turnovers<- read_csv("caused_turnovers_l.csv", col_select = 1:2)
clearing<- read_csv("clearing_pctg_l.csv", col_select = 1:2)
fo <- read_csv("fo_win_pctg.csv", col_select = 1:4)
goals_against<- read_csv("goals_against.csv", col_select = 1:2)
goals<- read_csv("goals_l.csv", col_select = 1:2)
groundballs<- read_csv("ground_balls_l.csv", col_select = 1:2)
man_down <- read_csv("man_down_defense_l.csv", col_select = 1:2)
man_up <- read_csv("man_up__offense_l.csv", col_select = 1:2)
margin <- read_csv("margin_l.csv", col_select = 1:2)
opp_clear <- read_csv("opp_clear_l.csv", col_select = 1:2)
points <- read_csv("points_l.csv", col_select = 1:2)
saves <- read_csv("saves_l.csv", col_select = 1:2)
shot <- read_csv("shot_pctg_l.csv", col_select = 1:2)
turnovers<- read_csv("turnovers_l.csv", col_select = 1:2)
shots_per_game <- read_csv("shots_per_game.csv", col_select = 1:3)
win_loss <- read_csv("win_loss_l.csv")

# joining
# students familiar with the purrr package could
# use the reduce function to reduce the amount of code

lax_2022_2023 <- 
  left_join(assists, caused_turnovers, by = "Team") %>%
  left_join(clearing, by = "Team") %>%
  left_join(fo, by = "Team")  %>%
  left_join(goals, by = "Team")  %>%
  left_join(goals_against, by = "Team")  %>%
  left_join(groundballs, by = "Team") %>%
  left_join(man_down, by = "Team") %>%
  left_join(man_up, by = "Team") %>%
  left_join(margin, by = "Team") %>%
  left_join(opp_clear, by = "Team") %>%
  left_join(points, by = "Team") %>%
  left_join(saves, by = "Team") %>%
  left_join(shot, by = "Team") %>%
  left_join(turnovers, by = "Team") %>%
  left_join(shots_per_game, by = "Team") %>%
  left_join(win_loss, by = "Team")

# cleaning
lax_2022_2023 <- lax_2022_2023 %>%
  separate(Team, into = c("Team","Conference"), sep = "\\(", extra = "merge")%>%
  mutate(Conference = str_remove_all(Conference,"\\)"),
         Team = str_trim(Team))%>%
  mutate(shots_per_game = Shots/Games)%>%
  select(-20, -21)

# saving
write_csv(x = lax_2022_2023, file = "lax_2022_2023.csv")
```

</details>

### Materials

[Class handout](single_prop_wksht.docx)

[Class handout - with solutions](single_prop_wksht_key.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
In this insightful exploration of NCAA Division I Lacrosse faceoff percentages, we have embarked on a statistical journey to evaluate a specific team's performance in comparison to league-wide statistics. Through the application of one sample proportion hypothesis testing, we gained valuable insights into the team's faceoff win percentage, unveiling strong evidence that their performance exceeded what we would expect by random chance alone. As we consider the broader implications of faceoffs in Division I Lacrosse, it becomes evident that faceoff wins play a pivotal role in team rankings and outcomes. The fact that Duke, the second-best team in the country, exhibited a faceoff win percentage above the league average highlights the significance of excelling in this aspect of the game. Winning faceoffs likely translates to higher goal-scoring opportunities, ultimately leading to more successful game outcomes.
:::
