---
title: "Boston Marathon 2023"
output: html_document
date: "2023-06-13"
---


# 11423 total female runners
# 15175 total male runners
# excluded from the total are non-binary, wheelchair, handcycles, and duo teams
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# All Women's Results by age group
```{r}
library(rvest)
library(tidyverse)


boston_marathon_1_page <- function(i, sex = c("W","M"), age = 1:13){
  
  base_url <- "https://results.baa.org/2023/?page="
  middle_url <- "&event=R&event_main_group=runner&num_results=1000&pid=list&pidp=start&search%5Bsex%5D="
  end_url <- "&search%5Bage_class%5D="
  
  
  url <- paste0(base_url, i, middle_url, sex, end_url, age)
  
  obs <- read_html(url) |> 
    html_nodes("li.list-group-item")
  
  tmp <- obs |> html_text(trim = TRUE)
  X <- tmp[-(1:2)] |> str_split(pattern = "(\n)+", simplify = TRUE)

  return(X)
}

# 18-39
boston_marathon_women_18_39 <- boston_marathon_1_page(i = 1, sex = "W", age = 1)
boston_marathon_women_18_39<-
  boston_marathon_women_18_39%>%
  as.data.frame()

         
for(i in 2:5){
  Sys.sleep(rpois(1, 3)+1)
additional_rows <- boston_marathon_1_page(i, sex = "W", age = 1)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_women_18_39 <- bind_rows("18-39" = boston_marathon_women_18_39, "18-39" = additional_rows, .id = "age_group")
}

######


# 40-44
boston_marathon_women_40_44 <- boston_marathon_1_page(i = 1, sex = "W", age = 2)
boston_marathon_women_40_44<-
  boston_marathon_women_40_44%>%
  as.data.frame()

  
additional_rows <- boston_marathon_1_page(i = 2, sex = "W", age = 2)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_women_40_44 <- bind_rows("40-44" = boston_marathon_women_40_44, "40-44" = additional_rows, .id = "age_group")

######
  
# 45-49
boston_marathon_women_45_49 <- boston_marathon_1_page(i = 1, sex = "W", age = 9)
boston_marathon_women_45_49<-
  boston_marathon_women_45_49%>%
  as.data.frame()

  
additional_rows <- boston_marathon_1_page(i = 2, sex = "W", age = 9)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_women_45_49 <- bind_rows("45-49" = boston_marathon_women_45_49, "45-49" = additional_rows, .id = "age_group")

#####

# 50-54
boston_marathon_women_50_54 <- boston_marathon_1_page(i = 1, sex = "W", age = 3)
boston_marathon_women_50_54<-
  boston_marathon_women_50_54%>%
  as.data.frame()

  
additional_rows <- boston_marathon_1_page(i = 2, sex = "W", age = 3)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_women_50_54 <- bind_rows("50-54" = boston_marathon_women_50_54, "50-54" = additional_rows, .id = "age_group")


#####


# 55-59
boston_marathon_women_55_59 <- boston_marathon_1_page(i = 1, sex = "W", age = 10)
boston_marathon_women_55_59<-
  boston_marathon_women_55_59%>%
  as.data.frame()%>%
  mutate(age_group = "55-59")%>%
  relocate(age_group, .before = V1)


##### 


# 60-64
boston_marathon_women_60_64 <- boston_marathon_1_page(i = 1, sex = "W", age = 4)
boston_marathon_women_60_64<-
  boston_marathon_women_60_64%>%
  as.data.frame()%>%
  mutate(age_group = "60-64")%>%
  relocate(age_group, .before = V1)
  

#####


# 65-69
boston_marathon_women_65_69 <- boston_marathon_1_page(i = 1, sex = "W", age = 11)
boston_marathon_women_65_69<-
  boston_marathon_women_65_69%>%
  as.data.frame()%>%
  mutate(age_group = "65-69")%>%
  relocate(age_group, .before = V1)
  

#####


# 70-74
boston_marathon_women_70_74 <- boston_marathon_1_page(i = 1, sex = "W", age = 8)
boston_marathon_women_70_74<-
  boston_marathon_women_70_74%>%
  as.data.frame()%>%
  mutate(age_group = "70-74")%>%
  relocate(age_group, .before = V1)
  

#####


# 75-79
boston_marathon_women_75_79 <- boston_marathon_1_page(i = 1, sex = "W", age = 12)
boston_marathon_women_75_79<-
  boston_marathon_women_75_79%>%
  as.data.frame()%>%
  mutate(age_group = "75-79")%>%
  relocate(age_group, .before = V1)
  

#####


# 80+
boston_marathon_women_80 <- boston_marathon_1_page(i = 1, sex = "W", age = 13)
boston_marathon_women_80<-
  boston_marathon_women_80%>%
  as.data.frame()%>%
  mutate(age_group = "80+")%>%
  relocate(age_group, .before = V1)

```
# binding rows
```{r}
boston_marathon_women <- rbind(boston_marathon_women_18_39, boston_marathon_women_40_44, boston_marathon_women_45_49, boston_marathon_women_50_54, boston_marathon_women_55_59, boston_marathon_women_60_64, boston_marathon_women_65_69, boston_marathon_women_70_74, boston_marathon_women_75_79, boston_marathon_women_80)
```




# All Men's Results by age group
```{r}
# 18-39
boston_marathon_men_18_39 <- boston_marathon_1_page(i = 1, sex = "M", age = 1)
boston_marathon_men_18_39<-
  boston_marathon_men_18_39%>%
  as.data.frame()

         
for(i in 2:6){
  Sys.sleep(rpois(1, 3)+1)
additional_rows <- boston_marathon_1_page(i, sex = "M", age = 1)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_men_18_39 <- bind_rows("18-39" = boston_marathon_men_18_39, "18-39" = additional_rows, .id = "age_group")
}


#####


# 40-44
boston_marathon_men_40_44 <- boston_marathon_1_page(i = 1, sex = "M", age = 2)
boston_marathon_men_40_44<-
  boston_marathon_men_40_44%>%
  as.data.frame()

         
for(i in 2:3){
  Sys.sleep(rpois(1, 3)+1)
additional_rows <- boston_marathon_1_page(i, sex = "M", age = 2)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_men_40_44 <- bind_rows("40-44" = boston_marathon_men_40_44, "40-44" = additional_rows, .id = "age_group")
}


#####


# 45-49
boston_marathon_men_45_49 <- boston_marathon_1_page(i = 1, sex = "M", age = 9)
boston_marathon_men_45_49<-
  boston_marathon_men_45_49%>%
  as.data.frame()

         
for(i in 2:3){
  Sys.sleep(rpois(1, 3)+1)
additional_rows <- boston_marathon_1_page(i, sex = "M", age = 9)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_men_45_49 <- bind_rows("45-49" = boston_marathon_men_45_49, "45-49" = additional_rows, .id = "age_group")
}


#####


# 50-54
boston_marathon_men_50_54 <- boston_marathon_1_page(i = 1, sex = "M", age = 3)
boston_marathon_men_50_54<-
  boston_marathon_men_50_54%>%
  as.data.frame()

         
for(i in 2:3){
  Sys.sleep(rpois(1, 3)+1)
additional_rows <- boston_marathon_1_page(i, sex = "M", age = 3)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_men_50_54 <- bind_rows("50-54" = boston_marathon_men_50_54, "50-54" = additional_rows, .id = "age_group")
}


#####


# 55-59
boston_marathon_men_55_59 <- boston_marathon_1_page(i = 1, sex = "M", age = 10)
boston_marathon_men_55_59<-
  boston_marathon_men_55_59%>%
  as.data.frame()

  
additional_rows <- boston_marathon_1_page(i = 2, sex = "M", age = 10)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_men_55_59 <- bind_rows("55-59" = boston_marathon_men_55_59, "55-59" = additional_rows, .id = "age_group")


#####


# 60-64
boston_marathon_men_60_64 <- boston_marathon_1_page(i = 1, sex = "M", age = 4)
boston_marathon_men_60_64<-
  boston_marathon_men_60_64%>%
  as.data.frame()

  
additional_rows <- boston_marathon_1_page(i = 2, sex = "M", age = 4)

additional_rows<- additional_rows%>%
    as.data.frame()

boston_marathon_men_60_64 <- bind_rows("60-64" = boston_marathon_men_60_64, "60-64" = additional_rows, .id = "age_group")


#####


# 65-69
boston_marathon_men_65_69 <- boston_marathon_1_page(i = 1, sex = "M", age = 11)
boston_marathon_men_65_69<-
  boston_marathon_men_65_69%>%
  as.data.frame()%>%
  mutate(age_group = "65-69")%>%
  relocate(age_group, .before = V1)


#####


# 70-74
boston_marathon_men_70_74 <- boston_marathon_1_page(i = 1, sex = "M", age = 8)
boston_marathon_men_70_74<-
  boston_marathon_men_70_74%>%
  as.data.frame()%>%
  mutate(age_group = "70-74")%>%
  relocate(age_group, .before = V1)


#####


# 75-79
boston_marathon_men_75_79 <- boston_marathon_1_page(i = 1, sex = "M", age = 12)
boston_marathon_men_75_79<-
  boston_marathon_men_75_79%>%
  as.data.frame()%>%
  mutate(age_group = "75-79")%>%
  relocate(age_group, .before = V1)


#####


# 80+
boston_marathon_men_80 <- boston_marathon_1_page(i = 1, sex = "M", age = 13)
boston_marathon_men_80<-
  boston_marathon_men_80%>%
  as.data.frame()%>%
  mutate(age_group = "80+")%>%
  relocate(age_group, .before = V1)

```
# binding rows
```{r}
boston_marathon_men <- rbind(boston_marathon_men_18_39, boston_marathon_men_40_44, boston_marathon_men_45_49,  boston_marathon_men_50_54, boston_marathon_men_55_59, boston_marathon_men_60_64, boston_marathon_men_65_69, boston_marathon_men_70_74, boston_marathon_men_75_79, boston_marathon_men_80)
```
# Cleaning 
```{r}
boston_marathon_women<- boston_marathon_women%>%
  mutate(gender = "W")

boston_marathon_men<- boston_marathon_men%>%
  mutate(gender = "M")

boston_marathon_2023 <- rbind(boston_marathon_men, boston_marathon_women)

boston_marathon_2023<-
boston_marathon_2023%>%
  separate(col = V8, into = c("D1","bib_number"), sep = 3)%>%
  separate(col = V11, into = c("D2","half_time"), sep = 4 )%>%
  separate(col = V12, into = c("D3","finish_net"), sep = 10)%>%
  separate(col = V13, into = c("D4","finish_gun"), sep = 10 )%>%
  select(1,2,3,4,5,8,10,14,16,18,19)%>%
  mutate(across(c(8,9,10), ~ hms(.)),
         half_time_sec = period_to_seconds(half_time),
         finish_net_sec = period_to_seconds(finish_net),
         finish_gun_sec = period_to_seconds(finish_gun))%>%
  rename(place_overall = V1, place_gender = V2, place_division = V3, 
         name = V4, team = V7)

write_csv(x = boston_marathon_2023, file = "boston_marathon_2023.csv")

boston_marathon_women<- boston_marathon_2023%>%
  filter(gender == "W")
boston_marathon_men<- boston_marathon_2023%>%
  filter(gender == "M")

write_csv(x = boston_marathon_men, file = "boston_marathon_men_2023.csv")
write_csv(x = boston_marathon_women, file = "boston_marathon_women_2023.csv")  

```












