---
title: "TwoWayANOVA_Worksheet"
Authors: Faith Rhinehart
execute: 
  echo: true
  warning: false
  error: true
format: 
  html:
    embed-resources: true
---

Figure skating is a sport where people perform routines on ice to music, combining athletic skill with artistic expression. Skaters compete in different categories like men's singles, women's singles, pairs (a man and a woman skating together), and ice dance (which focuses more on rhythm and movement). Each skater or team performs two routines: the short program and the free skate. The short program is a shorter routine with a list of required moves that every skater must include. Judges look at how well each move is done and how smoothly everything fits with the music. The free skate is longer and gives skaters more freedom to show their personal style and creativity. They still need to include certain types of moves, but they can choose how to put them together. Judges give scores for both routines based on how difficult the moves are, how well they’re done, and how artistic the performance is. The scores from both routines are added together, and the skater or team with the highest total wins.

Read in the Men's and Women's figure skating data:
```{r}
library(ggplot2)
library(tidyverse)
library(here)
library(readr)
library(dplyr)
library(ggthemes)
```


1) Change the `TP` variable in the women's data set into a <double> instead of a <character>


2) Combine the men and women data set into one data set


3) Conduct a two-way ANOVA with `Sex` as the interaction term. Make sure to include all parts of a formal hypothesis test.


4) Create a boxplot that models this interaction with `Sex` on the x-axis, `TP` on the y-axis, and fill by `Year`. (You will have to change `Year` to a factor). Comment on what you notice. 


5) Conduct another two-way ANOVA with `Sex` as a additive term. Make sure to include all parts of a formal hypothesis test.


6) Preform a Post-Hoc Tukey Test on the two-way ANOVA from question 5. Report that years that are significant and the years that are not. Comment on the significance of the `Sex` variable. 


7) Make a Pair Wise Comparisons for `Year` to visualize the significance between years.


8) If you completed the one-way ANOVA module and did the optional Pair Wise Comparisons, comment on how and why this two-way ANOVA letter's table is different from the one you did in the other one. 




