---
title: "Lacrosse PLL vs. NLL"
date: February 5, 2024
description: Comparing scoring rates between indoor and outdoor profesional lacrosse leagues.
author:
  - name: Jack Cowan
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
  - name: A.J. Dykstra
    affiliation:
    - ref: slu
  - name: Robin Lock
    affiliation:
    - ref: slu   
editor: 
  canonical: true
categories:
  - Difference in two means
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

This module examines the goals and shots in two prominent lacrosse leagues: the [Premier Lacrosse League (PLL)](https://premierlacrosseleague.com/){target="_blank"} and the [National Lacrosse League (NLL)](https://www.nll.com/){target="_blank"}. The PLL and NLL are highly regarded professional lacrosse leagues that feature top-tier athletes from around the world.

The PLL is played in an outdoor setting, following the [field lacrosse](https://en.wikipedia.org/wiki/Field_lacrosse){target="_blank"} format. This style of lacrosse is characterized by its larger field size, typically 110 yards by 60 yards. Field lacrosse involves 10 players per team and promotes a style of play that emphasizes long passes, intricate plays, and individual skills. Founded in 2019, the PLL operates with a touring model where teams travel to different cities each weekend, bringing the sport to a wide audience and fostering a festival-like atmosphere at each event. The league's modernized approach includes a strong emphasis on media presence and player engagement. The PLL features approximately 200 athletes across its teams.

In contrast, the NLL follows the [box lacrosse](https://en.wikipedia.org/wiki/Box_lacrosse){target="_blank"} format, which is played indoors on a smaller, enclosed field, generally 200 feet by 85 feet. Box lacrosse involves 6 players per team, and the gameplay is marked by frequent physical interactions, quick ball movements, and high-intensity transitions. Established in 1986, the NLL has a traditional franchise model with teams based in specific cities across the United States and Canada. This structure has cultivated strong local fan bases and deep community ties, contributing to the league's longevity. The NLL features approximately 500 athletes, many of which also play in the PLL.

These data, from the 2021-2022 seasons, allow for an analysis of goal-scoring within these leagues to identify differences between indoor (NLL) and outdoor (PLL) play. By examining goals and shots, we aim to understand how the environment and format of the game influence offensive strategies and overall scoring trends in professional lacrosse. It's important to recognize that outdoor field lacrosse and indoor box lacrosse are distinct sports, each with its own unique dynamics, rules, and playing styles. By acknowledging these nuances, we can may gain a deeper understanding of how various playing conditions and league structures impact statistical outcomes.


::: {.callout-note collapse="true" title="Activity Length" appearance="minimal"}
This activity would be suitable for an in-class example or can be modified to be a quiz or part of an exam.
:::

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
The learning goals associated with this module are:

*    Students will be able to test for a difference in means between two groups.
*    Students will be able to find a confidence interval for a difference in means between two groups.
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
This module requires students use a two-sample test and confidence interval (e.g., t-test or randomization) to compare the means of two groups. 

Students are expected to have access any equations and/or lecture notes to complete the activity.

Technology requirement: 

- The provided handout assumes that students can use technology such as calculators to perform a two-sample t-test and  interval for a difference in means between two groups.

- The raw data is provided to allow instructors to customize the handout to incorporate other forms of technology. e.g., Students can use software such as Minitab to calculate test statistics and p-values for a t-test or [StatKey](https://www.lock5stat.com/StatKey/){target="_blank"} for simulation based inference.

:::

### Data

The data set has 162 rows with 9 columns. Each row represents a single lacrosse match either in the Premier Lacrosse League or the National Lacrosse League during the 2021-2022 season.

Download data: [lacrosse_pll_nll_2021-2022.csv](lacrosse_pll_nll_2021-2022.csv)

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable       | Description                                                    |
|------------------|------------------------------------------------------|
| League         | The Premier Lacrosse league and the National Lacrosse League   |
| Away_team      | The traveling team                                             |
| Home_team      | The hosting team                                               |
| Away_shots     | How many shots the `Away_team` had on net                      |
| Home_shots     | How many shots the `Home_team` had on net                      |
| Away_goals     | How many goals the `Away_team` had on net                      |
| Home_goals     | How many goals the `Home_team` had on net                      |
| Goals | The total amount of goals scored each game                     |
| Goals_per_48   | The average amount of goals for the first 48 minutes of a game |

</details>


#### Data Sources
Premier Lacrosse League stats. Premier Lacrosse League Stats. (n.d.). [https://stats.premierlacrosseleague.com/](https://stats.premierlacrosseleague.com/)

Player stats. NLL. (2023, January 26). [https://www.nll.com/stats/all-player-stats/](https://www.nll.com/stats/all-player-stats/)



### Materials

The data and worksheet associated with this module are available for download through the following links. 

* [lacrosse_pll_nll_2012-2022.csv](lacrosse_pll_nll_2021-2022.csv) - Dataset with game-by-game shots and goals scored for both leagues in the 2021-2022 season.. 

* [lacrosse_pll_vs_nll_t-test_worksheet.docx](lacrosse_pll_vs_nll_t-test_worksheet.docx)- Activity worksheet to compare scoring and shots between indoor and outdoor leagues using t-distributions.

* [lacrosse_pll_vs_nll_randomization_worksheet.docx](lacrosse_pll_vs_nll_randomization_worksheet.docx)- Activity worksheet to compare scoring and shots between indoor and outdoor leagues using randomization tests implements via [StatKey](https://www.lock5stat.com/StatKey/){target="_blank"}.



Sample solutions to the worksheets 

* [lacrosse_pll_vs_nll_t-test_worksheet_key.docx](lacrosse_pll_vs_nll_t-test_worksheet_key.docx) - Activity worksheet using t-distributions with sample solutions. 

* [lacrosse_pll_vs_nll_randomization_worksheet_key.docx](lacrosse_pll_vs_nll_randomization_worksheet_key.docx) - Activity worksheet using randomization tests with sample solutions. 


::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Students should notice that while no discernible difference between average goals per game was discovered, after adjusting for the length of the game, PLL (i.e., the 48-minute outdoor league) has the higher rate per 48-minutes.

Further, students will ideally see how a confidence interval can be used to supplement the conclusion of a hypothesis test by bringing effect sizes into the interpretation in addition to statistical significance.
:::


