---
title: "NCAA D1 Expenditures"
author: Ivan Ramler, Denali Stevens
standalone: true
---

We have data on the reported revenues and expenditures of NCAA D1 schools by sport (for 2019). 


```{r, echo = FALSE}
library(tidyverse) |> suppressPackageStartupMessages()
library(crosstalk) |> suppressPackageStartupMessages()
library(plotly) |> suppressPackageStartupMessages()
```

```{r, echo = FALSE}
ncaa_div1_rev_expend <- read_csv("ncaa_div1_rev_expend.csv", show_col_types = FALSE)
```

```{r, echo = FALSE}
expensive_sports <- ncaa_div1_rev_expend |>
  filter(year == max(year)) |>
  group_by(sports) |>
tally() |>
  slice_max(order_by = n, n = 12) |>
  filter(sports != "Football") |>
  filter(sports != "Basketball") |>
  pull(sports) |>
  unique()

sports2 <- ncaa_div1_rev_expend |>
  filter(year == max(year)) |>
  filter(sports %in% expensive_sports) |>
  drop_na() |>
  filter(total_rev_menwomen != total_exp_menwomen) |>
  select(institution_name, total_rev_menwomen, total_exp_menwomen, sports)


```

```{r, echo = FALSE}
gp <- ggplot(data = sports2, aes(x = sports, y = total_exp_menwomen/1000000, fill = sports)) +
  geom_boxplot(color = "black") +
  theme(legend.position="none") +
  theme_minimal() +
  labs(y = "2019 Total Expenditures (USD mil)")

#gp

```


```{r, echo = FALSE}
gp2 <- ggplot(data = sports2, aes(x = total_exp_menwomen/1000000)) +
  geom_histogram(color = "black") +
  theme(legend.position="none") +
  theme_minimal() +
  labs(x = "2019 Total Expenditures (USD mil)") +
  facet_wrap(~sports, scales = "free_y")
```

What interesting questions can be asked with this data?

Notes: 

- I've removed Football and Basketball
- I've removed rows where the expenditures exactly equal the revenue as I deem those to be an accounting trick and not real.


```{r}
library(crosstalk)
library(d3scatter)
shared_sports2 <- SharedData$new(sports2)
bscols(widths = c(3,NA),
  list(
#    filter_checkbox("cyl", "Cylinders", shared_mtcars, ~cyl, inline = TRUE),
#    filter_slider("hp", "Horsepower", shared_mtcars, ~hp, width = "100%"),
    filter_select("auto", "Sports", shared_sports2, ~sports)
  ),
  d3scatter(shared_sports2, ~total_exp_menwomen, ~total_rev_menwomen, ~factor(sports), width="100%", height=250))
```




```{r, echo = FALSE}
#htmlwidgets::saveWidget(plt, file = "myplot.html")

```

