---
title: "2024 Dakar Rally Handout"
format: 
  html:
    embed-resources: true
---

In January of 2024, Saudi Arabia hosted the Dakar Rally, an epic off-road endurance event spanning thousands of kilometers across the rugged terrain. With 
drivers navigating deserts, mountains, and dunes, this race poses formidable challenges for all sorts of vehicles, such as bikes, cars, and trucks. Our 
focus will be on exploring the bikers ranking based off the racers time statistics and driver information.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
riders <- read_csv(here::here("Dakar Rally/data/dakarRally_bikes_data.csv"))
```


# 1.

**Given the data, fit a linear model that uses Hours, Minutes, Seconds, Penalty_Hours, Penalty_Minutes, Penalty_Seconds to predict riders ranking.**

## a.

**Fit the model **



## b.

**Interpret the coefficient for $\hat\{beta_{Hours}}$ & $\hat\{beta_{Penalty_Hours}}$**




## c.

**Test the significance of $\hat{\beta_{Minutes}}$**




## c.

**Now, looking $\hat{\beta_{Hours}}$, conduct a 95% confidence interval.**






# 2.	

**Given the data, create a summary output that has the mean time as penalty times for each stage (make sure to incorporate minutes and seconds).**

## a. 

**Create Summary output**



## b.

**What stage in the race on average takes the riders the longest to complete?**




## c.
**At what stage did the rider's seem to gain the most penalties on average?**



## d. 

**Determine how many riders started the event versus ended it. How many rider's dropped out or were disqualified?**





# 3.

**Based on the summary output, which stage(s) in the race are the most significant towards overall ranking and why?**


