---
title: "Disc Golf Pro Tour - Driving or Putting?"
description: What is more correlated with success on the Disc Golf Pro Tour, Driving or Putting?
author:
  - name: Gavin Cassidy
    affiliation:
      - id: slu
        name: St. Lawrence University
  - name: Ivan Ramler
    email: iramler@stlawu.edu
    affiliation:
      - ref: slu
date: June 13, 2024
categories:
  - Correlation
---

## Module

### Introduction

Disc Golf is a rapidly growing sport with a full fledged professional circuit and tournaments all over the world. The Disc Golf Pro Tour ([DGPT](https://www.dgpt.com/){target="_blank"}) allows top level players to compete week after week across the United States, Canada, and Europe. With top level tournaments offering over \$100,000 of prize money at many tournaments, players need a vast skill set to compete at the highest level. Similarly to ball golf, the two main types of shots in disc golf are driving and putting. Driving happens from the teeing area and putting happens on the 'green' where players try to throw their disc into the basket.

The data set for this activity was taken from DGPT and Major tournament statistics found on the Professional Disc Golf Association's official statistics website, [StatMando](https://statmando.com/){target="_blank"}. Each row contains a player who has played at least 40% of rounds during the DGPT season and has finished the tournament above the cash line at least once. Each row has the name of the player along with a collection of statistics covering a variety of different skills including driving, putting, and performance.

::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
The learning objectives associated with this module are:

-   Being able to use correlation coefficients to compare the connection between quantitative variables.

-   Reading a correlation table
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
-   Students are expected to have been introduced to the concept of correlation.
:::


::: {.callout-note collapse="true" title="Technology requirement" appearance="minimal"}
- The no tech version can be completed without any additional technology.

- The tech version will require students to produce graphics and correlation matrices using statistical software.
:::

### Data

This data set has 97 rows with each rows containing the (approximately) first half of the 2024 season statistics for a player. These rows have 25 columns with season statistics.

Up to date statistics can be obtained using the code available from the [SCORE Data Repository](https://data.scorenetwork.org/disc_sports/DGPT24.html){target="_blank"}

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable       | Description                                                                   |
|--------------------------|----------------------------------------------|
| player         | player name                                                                   |
| birdie_avg     | the average number of birdies from an 18 hole round                           |
| bogey_avg      | the average number of bogeys from an 18 hole round                            |
| PKD            | the percentage of shots a player has 'parked' (within 10 ft of the basket)    |
| C1R            | the percent of shots throw within 'Circle 1'(0-33ft) in regulation            |
| C2R            | the percent of shots throw within 'Circle 2'(33-66ft) in regulation           |
| FWY            | the percent fairways hit with drives                                          |
| SCR            | the percent of successful 'scrambles' the player achieves                     |
| OB/18          | the average total out of bounds shots for 18 holes                            |
| C1X            | the percent of putts made from C1 excluding tap in putts(0-10ft)              |
| C2P            | the percent of putts made from C2 (33-66ft)                                   |
| tot_SG:TG      | the total 'Strokes Gained' on the rest of the field from the tee to the green |
| tot_SG:P       | the total 'Strokes Gained' on the rest of the field putting                   |
| events         | total events played for the 2024 DGPT season                                  |
| rounds         | total rounds played for the 2024 DGPT season                                  |
| wins           | wins from the 2024 DGPT season                                                |
| podiums        | total podium placements from the 2024 DGPT season                             |
| top_10s        | total top 10 placements from the 2024 DGPT season                             |
| top_20s        | total top 20 placements from the 2024 DGPT season                             |
| avg_place      | average event placement from the 2024 DGPT season                             |
| top_10%        | percent of events where the player placed in the top 10                       |
| top_20%        | percent of events where the player placed in the top 20                       |
| total_earnings | the players total earnings from the 2024 DGPT season                          |
| total_strokes  | the total number of shots the player has taken during the DGPT season         |

::: {.callout-note collapse="true" title="Important Disc Golf Terms" appearance="minimal"}
**Parked(PKD):** When a player throws their disc within 10 feet of the basket with a tee shot on par 3s or an approach shot on par 4s and 5s. A score of eagle or better also counts as a shot being parked.

**Circle 1 in Regulation(C1R):** When a player's disc comes to rest within 10m(33ft) of the basket in the expected amount of shots. This is their tee shot on a par 3, 2nd shot on a par 4, and third shot on a par 5. C1 is defined by a 10m circle around the basket.

**Circle 2 in Regulation(C2R):** This has the same definition as Circle 1 in Regulation, but Circle 2 extends to within 20m(66ft) of the basket.

**Fairways Hit(FWY):** This is the percent of holes where the player lands on the fairway with their drive. This includes being inside Circle 1 or 2 on a drive.

**Scramble(SCR):** A scramble is when a player scores par or better on a hole after missing the fairway or being out-of-bounds. Scramble percentage is the percentage of holes where a player scored par or better after an errant drive.

**Circle 1X putting(C1X):** The putting percentage of the player from within Circle 1 (10m/66ft), excluding tap in putts within 10ft of the basket.

**Circle 2 putting(C2P):** The putting percentage of the player from Circle 2 (10m-20m/33ft-66ft).

**Strokes Gained Tee to Green(SG:TG):** This is the number of strokes by which the player has exceeded the average throwing performance of the field on drives and approaches.

**Strokes Gained Putting(SG:P):** This is the number of strokes by which the player has exceeded the average putting performance of the field in circle 1 and 2.
:::

**Data Source**

The data is obtained from the PDGA's official statistics provider [StatMando](https://statmando.com/){target="_blank"}.

</details>

### Materials

[DGPT24.csv](DGPT24.csv) - data set containing statistics from the 2024 DGPT season found on the [SCORE Network Data Repository](https://data.scorenetwork.org/){target="_blank"}

[DGPT24_questions.docx](DGPT24_questions.docx) - questions about correlation between total earnings and putting and driving

[DGPT24_questions_tech.docx](DGPT24_questions_tech.docx) - questions about correlation where students use the data to build their own solutions

Solutions for questions:

[DGPT24_questions_ans.docx](DGPT24_questions_ans.docx)

[DGPT24_questions_tech_ans.docx](DGPT24_questions_tech_ans.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
Students should find that there is a stronger correlation between driving and performance statistics than putting and performance statistics.
:::
