---
title: "2023 Boston Marathon"
date: February 5, 2024
description: Describing finish time for runners in the 2023 Boston Marathon
categories:
  - histogram
  - summary statistics
  - z-scores
---

## Module

Please note that these material have not yet completed the required pedagogical and industry peer-reviews to become a published module on the SCORE Network. However, instructors are still welcome to use these materials if they are so inclined.

### Introduction

For this activity, you will be exploring the result times from female and male runners that finished the 2023 Boston Marathon. 

In particular, you will examine both visualizations and summary statistics of result times to explore the variation in finish times as well as use comparative techniques, such as z-scores, to compare and contrast male and female participants.



::: {.callout-note collapse="true" title="Learning Objectives" appearance="minimal"}
By the end of the activity, you will be able to:

1.  Analyze structures and distributions of histograms
2.  Use basic summary statistics to assess center and spread
3.  Calculate further relevant metrics for quantitative data
4.  Calculate and compare z-scores for individual cases
:::

::: {.callout-note collapse="true" title="Methods" appearance="minimal"}
For this activity, students will primarily use basic concepts of histograms and boxplots to analyze distributions. Students will also require formulas for deviation, IQR, standard deviation, fences, and z-score.
:::

::: {.callout-note collapse="true" title="Technology Requiremens" appearance="minimal"}
The provided worksheets to not require any specific statistical software. (Although they do require access to a calculator.) 

Since the data is provided, instructors are encouraged to modify the worksheets to have student construct visualizations and calculate summary statistics using whichever software they choose.
:::

### Data

The data set contains 26598 rows and 15 columns. Each row represents a runner who completed the Boston Marathon in 2023

Download data: [boston_marathon_2023.csv](boston_marathon_2023.csv)

<details>
<summary><b>Variable Descriptions</b></summary>

| Variable | Description |
|----|----------------------------|
| age_group | age group of the runner |
| place_overall | finishing place of the runner out of all runners |
| place_gender | finishing place of runner among the same gender |
| place_division | finishing place of runner among runners of the same gender and age group |
| name | name of runner |
| gender | gender of runner |
| team | team the runner is affiliated with |
| bib_number | bib number of runner |
| half_time | half marathon time of runner |
| finish_net | finishing time timed from when they cross the starting gate |
| finish_gun | finishing time of runner timed from when the starter gun is fired |
| age_group | age group of the runner |
| half_time_sec | half marathon time in seconds |
| finish_net_sec | net finish in seconds |
| finish_gun_sec | gun finish in seconds |
| finish_net_minutes | net finish in minutes |



**Data Source**

[Boston Athletic Association](https://www.baa.org){target="_blank"}

</details>

### Materials

[Class handout](boston_marathon_wksht.docx)

[Class handout - with solutions](boston_marathon_wksht_key.docx)

::: {.callout-note collapse="true" title="Conclusion" appearance="minimal"}
In conclusion, the Boston Marathon Times worksheet provides valuable learning opportunities for students in several key areas. Firstly, it introduces them to the calculation of essential summary statistics, allowing them to gain a deeper understanding of the distribution of result times. Secondly, by identifying outliers above or below the upper fences, students can recognize and analyze exceptional performances in the marathon. Lastly, the calculation of z-scores enables students to compare and contrast the remarkable achievements of the top female and male finishers, shedding light on their talent in their respective fields. Overall, this worksheet allows students to critically analyze the 2023 marathon result data and draw meaningful conclusions about the extraordinary performances of athletes in the race.
:::

### Authors

Fill in later
